### ISSUE TITLE
LobiList instance object not updated after item updated or added

### ISSUE THREAD

**Issue by bobleponge22** [arboshiki/lobilist#1]
The LobiList instance object is not updated after item updated or added.

In the attached sample derived from the demo example:
* a list with 2 items is initialized,
* In the browser :
    - one of the two items is modified
    - a new item is added
* a button in the page fires an alert() with the titles of each item

=> $items is not updated as expected, and only contains initial items

[sample.zip](https://github.com/arboshiki/lobilist/files/270899/sample.zip)

**Comment by bobleponge22** [comment]
Hi, I tried 1.0.6 but the result is the same. 
I uplaoded the full sample. 
[sample2.zip](https://github.com/arboshiki/lobilist/files/303344/sample2.zip)
Can you check?

**Comment by arboshiki** [comment]
I have made some changes regarding `$items`.

Now `List` has `$items` property (of object type instead of array where key is todo id and value is object) which is updated. `$options.items` contains only initial items.

Try this code
```
var tst = $('#todo-lists-demo-controls').data('lobiList').$lists[0].$items;
        	var str = "";
        	for(var i in tst)
        	{
        		str = str + tst[i].title+" \n"; 
        	}
            alert(str);
```
