### ISSUE TITLE
LobiList not allow events to add items are disabled when loading the page.

### ISSUE THREAD

**Issue by Noel-A-Gonzalez** [arboshiki/lobilist#2]
LobiList not allow disable the events when the page loads, as for example if I have 5 items , when loading the page shows me 5 Sometimes an alert(), which placed it myself, that way if I want to add a items , can not use the event .

**Comment by arboshiki** [comment]
Can you please write it in english? I can't understand Spanish.

**Comment by arboshiki** [comment]
Ok.
Thank you.
Soon I plan to release new version and I will fix this.
